[colors.primary]
background = "#c5c5c5"
foreground = "#444444"

[colors.cursor]
text = "#eeeeee"

[colors.normal]
black = "#eeeeee"
red = "#af0000"
green = "#008700"
yellow = "#5f8700"
blue = "#0087af"
magenta = "#8700af"
cyan = "#005f87"
white = "#878787"

[colors.bright]
black = "#bcbcbc"
red = "#af0000"
green = "#008700"
yellow = "#5f8700"
blue = "#0087af"
magenta = "#8700af"
cyan = "#005f87"
white = "#eeeeee"
